---
output:
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## HW 1
## Tyler Sulsenti
```{r}
X <- c(0.2,1.2,0.9,2.2,3.2,3.1,2.3,1.5,3.0,2.6 ,9.0)
Y <- c(1.1, 2.3 , 1.1 , 3.6 , 0.1 , 4.8 , 6.5 , 7.8 , 8.0 , 9.4 , 9.8)

#i
hist(X)
#The distrubution of the Historgram of X is Right skewed. 
#Most of the data is on the left side of the plot and the tail is on the right side. 
#The median is 2.3 and we use median becuase the data is skewed.

pie(X)

hist(Y)
#The distrubution of the Histogram of Y is a bimodial distrubtion. 
#It has two peaks of the same height.

pie(Y)

#ii
#Boxplot for X
boxplot(X, horizontal = TRUE)

#Five number summary for X
summary(X)

#variance for X
var(X)

#Outliers:
#For X, there is one outlier and it is 9.0

#Boxplot for Y
boxplot(Y, horizontal = TRUE)

#Five number summary for Y
summary(Y)

#Variance for Y
var(Y)

#Outliers
#There are no outliers for Y according to the boxplot

#iii
#Scatterplot of (X,Y)
plot(X,Y)
abline(lm(Y~X))
#Correlation Coefficient is 0.5571167 based on
cor(X,Y)
#Since the correlation is postive, this means that the linear association
#between X and Y is positively correlated. Therefore, as X increases, so will Y

#iv
#Yes there is an outlier at (9.0,9.8)
#Now to remove
X <- c(0.2,1.2,0.9,2.2,3.2,3.1,2.3,1.5,3.0,2.6)
Y <- c(1.1 , 2.3 , 1.1 , 3.6 , 0.1 , 4.8 , 6.5 , 7.8 , 8.0 , 9.4)
#Re-Plot
plot(X,Y)
abline(lm(Y~X))
#Correlation Coefficient is 0.3873604 based on
cor(X,Y)


#v
#The difference between iii and iv is that the new correlation coefficient in iv is 
#lower and closer to 0 than the one in iii. This means that the relationship between
#X and Y is less linear than before.

#vi
#normal QQ plot of X
qqnorm(X)
qqline(X)
#normal QQ plot of Y
qqnorm(Y)
qqline(Y)
#The data in X is more likely to be of normal distrubtion because the data represents a
#more straight diagonal line.
```

