# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'ClientServer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    pod 'SwiftSocket'
    end

  # Pods for Client server

  target 'ClientServerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ClientServerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

